const ActionTypes = {
  LOAD_IMAGE: 'LOAD_IMAGE',
  TOGGLE_IMAGE: 'TOGGLE_IMAGE',
  TOGGLE_DRAW_CANVAS: 'TOGGLE_DRAW_CANVAS',
  PIXEL_COLOR_CHANGED: 'PIXEL_COLOR_CHANGED',
  RESET_IMAGE: 'RESET_IMAGE',
  INVERT_IMAGE: 'INVERT_IMAGE',
  GRAYSCALE_IMAGE: 'GRAYSCALE_IMAGE',
  BINARIZE_IMAGE: 'BINARIZE_IMAGE',
  CHANGE_CONTRAST: 'CHANGE_CONTRAST',
  CHANGE_BRIGHTNESS: 'CHANGE_BRIGHTNESS',
  TOGGLE_NAV_ITEM: 'TOGGLE_NAV_ITEM',
  TOGGLE_EXPANDED_DATA: 'TOGGLE_EXPANDED_DATA',
  SET_SLIDER_VALUE: 'SET_SLIDER_VALUE',
  SET_COLOR_PALETTE_VALUE: 'SET_COLOR_PALETTE_VALUE',
  SET_SELECTOR_VALUE: 'SET_SELECTOR_VALUE',
  SAVE_IMAGE_PROFILE: 'SAVE_IMAGE_PROFILE',
  UPDATE_DRAW_CANVAS: 'UPDATE_DRAW_CANVAS',
  SAVE_LINE_POINTS: 'SAVE_LINE_POINTS',
  SAVE_BRIGHTNESS_PLOT_PROPS: 'SAVE_BRIGHTNESS_PLOT_PROPS',
  APPLY_SOLD_PEPPER_NOISE: 'APPLY_SOLD_PEPPER_NOISE',
  APPLY_SINUS_NOISE: 'APPLY_SINUS_NOISE',
  LINE_FILTERING: 'LINE_FILTERING',
  NOT_LINE_FILTERING: 'NOT_LINE_FILTERING',
  FIND_BORDERS: 'FIND_BORDERS'
};

export default ActionTypes;
