export default {
  BIN_DATA: 'BIN_DATA',
  CONTRAST_DATA: 'CONTRAST_DATA',
  BRIGHTNESS_DATA: 'BRIGHTNESS_DATA',
  IMAGE_BRIGHTNESS_PROFILE: 'IMAGE_BRIGHTNESS_PROFILE',
  LINE_BRIGHTNESS_PROFILE: 'LINE_BRIGHTNESS_PROFILE',
  IMAGE_DESCRIPTION: 'IMAGE_DESCRIPTION',
  LINE_COLOR: 'LINE_COLOR',
  LINE_PROFILE_NAV_ELEM: 'LINE_PROFILE_NAV_ELEM',
  DIAGRAM_BRIGHTNESS_NAV_ELEM: 'DIAGRAM_BRIGHTNESS_NAV_ELEM',
  SOLD_PEPPER_NOISE_ELEM: 'SOLD_PEPPER_NOISE_ELEM',
  SINUS_NOISE_ELEM: 'SINUS_NOISE_ELEM'
};
